background #16181A
foreground #EAEAEA

cursor #F1FF5E
cursor_text_color #FF5EA0

selection_background none
selection_foreground none

# Normal colors
color0 #1E2124
color1 #FF6E5E
color2 #5EFF6C
color3 #FFBD5E
color4 #5EA1FF
color5 #BD5EFF
color6 #5EF1FF
color7 #ACACAC

# Bright colors
color8 #7B8496
color9 #FF5EA0
color10 #15FF00
color11 #F1FF5E
color12 #0095FF
color13 #FF5EF1
color14 #00FFEA
color15 #FFFFFF
