# cyberterm-light — Kitty terminal config

background #ffffff
foreground #1e2124

cursor #d17c00
cursor_text_color #d11500

selection_background none
selection_foreground none

# Normal colors
color0 #eaeaea
color1 #d11500
color2 #008b0c
color3 #d17c00
color4 #0057d1
color5 #a018ff
color6 #008c99
color7 #3c4048

# Bright colors
color8 #7b8496
color9 #f40064
color10 #008b23
color11 #997b00
color12 #0034d1
color13 #d100bf
color14 #007399
color15 #16181a
